[tool.poetry]
name = "luke"
version = "0.1.0"
description = ""
authors = ["Ikuya Yamada <ikuya@ousia.jp>"]

[tool.poetry.dependencies]
python = "^3.6.1"
Click = "*"
joblib = "*"
marisa-trie = "*"
numpy = "*"
tensorflow = "1.15.3"
torch = "1.2.0"
transformers = "2.4.1"
tqdm = "*"
ujson = "*"
wikipedia2vec = "*"
comet-ml = { version = "*", optional = true }
optuna = { version = "*", optional = true }
seqeval = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
black = "^19.10b0"
mypy = "^0.780"

[tool.poetry.scripts]
luke = 'luke:cli.cli'

[tool.black]
line-length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
